### ISSUE TITLE
film year should have values only between 1900-2024

### ISSUE THREAD

**Issue by Japoivvb** [Tomvsa/tomas_villaseca_uf3_p1#1]
1. please update logic to insert data in specific range to avoid strange years in our reports about movies by decade

2. create a hotfix branch to fix it

3. set label as bug to be tracked

4. commit message with #numberIssue verb(in 3rd person) +  details
 
5. create pull request and merge to main branch mention me with @name when it is ready in order to close issue please

**Comment by Tomvsa** [comment]
ready to merge @Japoivvb
