### ISSUE TITLE
Keep current data of database in case rollback/migrate

### ISSUE THREAD

**Issue by Japoivvb** [Tomvsa/tomas_villaseca_uf3_p1#2]
1. update (if it is posible) migrations files to keep current data in case rollback is executed
you can save current data in some temporal folder in rollback and be fetch again when migrate is launched

2. create a enhancement branch to develop it

3. set label as development to be tracked

4. commit message with #numberIssue verb(in 3rd person) +  details

5. create pull request and merge to main branch mention me with @name when it is ready in order to close issue please

**Comment by Tomvsa** [comment]
ready to merge @Japoivvb
