### ISSUE TITLE
Create a new API route to get all films and its corresponding actors

### ISSUE THREAD

**Issue by Japoivvb** [Tomvsa/tomas_villaseca_uf3_p1#7]
1. Implement logic to show all films+actors data, for each film there should be an array with actors data related

2. create a enhancement branch to develop it

3. set label as development to be tracked

4. commit message with #numberIssue verb(in 3rd person) +  details

5. create pull request and merge to main branch mention me with @name when it is ready in order to close issue please

**Comment by Tomvsa** [comment]
@Japoivvb  ready to merge
